reference:
  name: "mm10"
  chrom_sizes_url: "https://www.encodeproject.org/files/mm10_no_alt.chrom.sizes/@@download/mm10_no_alt.chrom.sizes.tsv"
  fasta_url: "https://www.encodeproject.org/files/mm10_no_alt_analysis_set_ENCODE/@@download/mm10_no_alt_analysis_set_ENCODE.fasta.gz"
  blacklist_url: "https://raw.githubusercontent.com/Boyle-Lab/Blacklist/master/lists/Blacklist_v1/mm10-blacklist.bed.gz"
  motif_url: "https://hocomoco14.autosome.org/final_bundle/hocomoco14/H14CORE/formatted_motifs/H14CORE_meme_format.meme"

samples:
    #  p53_WT:
    #    experiment: "SRR832846"
    #    control: "SRR832847"
  p53_KO:
    experiment: "SRR832848"
    control: "SRR832849"

bpnet_params:
  input_len: 2114
  output_len: 1000
  macs_g: "mm"
  splits:
    train: ["chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", "chr10", "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", "chr17"]
    val: ["chr18"]
    test: ["chr19"]
  outlier_quantile: 0.99
  outlier_scale_factor: 1.2
  neg_to_pos_ratio: 4 # This value is used when creating the gc background
  ratio: 0.33 # This value is used for creating the training dataset
  flank_size: 1057
  filters: 64
  num_dilation_layers: 8
  conv_kernel_size: 21
  profile_kernel_size: 75

other_MEF_tracks:
  reference:
    atac: ["SRR18371806", "SRR18371805", "SRR18371804"] # rep1, rep2, rep3
    pretrained_bias_url: "https://storage.googleapis.com/chrombpnet_data/input_files/bias_models/ATAC/ENCSR868FGK_bias_fold_0.h5" 

